spring:
  application:
    name: aspect-demo
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8182
    servlet:
        context-path: /asp-demo
---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test_job?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis
mybatis:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml
  # 实体扫描，mybatis 驼峰命名映射
  typeAliasesPackage: com.algebra.aspect.domain
