package rules2;
dialect  "java";

import com.algebra.aspect.drools.fact.Address;
import com.algebra.aspect.drools.fact.Phone;

rule "校验邮编格式&电话号码格式"
    when
        $address :Address(postcode != null, postcode matches "([0-9]{5})");
        $phone :Phone(phoneNo != null, phoneNo matches "(^((13[0-9])|(14[5,7,9])|(15([0-3]|[5-9]))|(17[0,1,3,5,6,7,8])|(18[0-9])|(19[8|9])|(16[6]))\\d{8}$)");
    then
        System.out.println("[drools]邮政编码格式(5位)校验通过！---");
        System.out.println("[drools]电话号码格式(手机)校验通过！---");
end
